package com.xinyi.dao;

import com.xinyi.bean.Picking;
import com.xinyi.bean.PickingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PickingMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table picking
	 * @mbg.generated  Sat Jul 20 11:45:26 CST 2019
	 */
	long countByExample(PickingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table picking
	 * @mbg.generated  Sat Jul 20 11:45:26 CST 2019
	 */
	int deleteByExample(PickingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table picking
	 * @mbg.generated  Sat Jul 20 11:45:26 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table picking
	 * @mbg.generated  Sat Jul 20 11:45:26 CST 2019
	 */
	int insert(Picking record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table picking
	 * @mbg.generated  Sat Jul 20 11:45:26 CST 2019
	 */
	int insertSelective(Picking record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table picking
	 * @mbg.generated  Sat Jul 20 11:45:26 CST 2019
	 */
	List<Picking> selectByExample(PickingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table picking
	 * @mbg.generated  Sat Jul 20 11:45:26 CST 2019
	 */
	Picking selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table picking
	 * @mbg.generated  Sat Jul 20 11:45:26 CST 2019
	 */
	int updateByExampleSelective(@Param("record") Picking record, @Param("example") PickingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table picking
	 * @mbg.generated  Sat Jul 20 11:45:26 CST 2019
	 */
	int updateByExample(@Param("record") Picking record, @Param("example") PickingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table picking
	 * @mbg.generated  Sat Jul 20 11:45:26 CST 2019
	 */
	int updateByPrimaryKeySelective(Picking record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table picking
	 * @mbg.generated  Sat Jul 20 11:45:26 CST 2019
	 */
	int updateByPrimaryKey(Picking record);
}