package com.xinyi.bean;

import java.util.Date;

public class Picking {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column picking.id
	 * @mbg.generated  Sat Jul 20 11:45:26 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column picking.materials
	 * @mbg.generated  Sat Jul 20 11:45:26 CST 2019
	 */
	private String materials;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column picking.time
	 * @mbg.generated  Sat Jul 20 11:45:26 CST 2019
	 */
	private Date time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column picking.admin
	 * @mbg.generated  Sat Jul 20 11:45:26 CST 2019
	 */
	private String admin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column picking.plus
	 * @mbg.generated  Sat Jul 20 11:45:26 CST 2019
	 */
	private String plus;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column picking.id
	 * @return  the value of picking.id
	 * @mbg.generated  Sat Jul 20 11:45:26 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column picking.id
	 * @param id  the value for picking.id
	 * @mbg.generated  Sat Jul 20 11:45:26 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column picking.materials
	 * @return  the value of picking.materials
	 * @mbg.generated  Sat Jul 20 11:45:26 CST 2019
	 */
	public String getMaterials() {
		return materials;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column picking.materials
	 * @param materials  the value for picking.materials
	 * @mbg.generated  Sat Jul 20 11:45:26 CST 2019
	 */
	public void setMaterials(String materials) {
		this.materials = materials;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column picking.time
	 * @return  the value of picking.time
	 * @mbg.generated  Sat Jul 20 11:45:26 CST 2019
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column picking.time
	 * @param time  the value for picking.time
	 * @mbg.generated  Sat Jul 20 11:45:26 CST 2019
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column picking.admin
	 * @return  the value of picking.admin
	 * @mbg.generated  Sat Jul 20 11:45:26 CST 2019
	 */
	public String getAdmin() {
		return admin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column picking.admin
	 * @param admin  the value for picking.admin
	 * @mbg.generated  Sat Jul 20 11:45:26 CST 2019
	 */
	public void setAdmin(String admin) {
		this.admin = admin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column picking.plus
	 * @return  the value of picking.plus
	 * @mbg.generated  Sat Jul 20 11:45:26 CST 2019
	 */
	public String getPlus() {
		return plus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column picking.plus
	 * @param plus  the value for picking.plus
	 * @mbg.generated  Sat Jul 20 11:45:26 CST 2019
	 */
	public void setPlus(String plus) {
		this.plus = plus;
	}
}