package com.xinyi.bean;

import java.util.Date;

public class XinyiModifyhistory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xinyi_modifyhistory.modifyId
     *
     * @mbg.generated Sat Jul 06 15:36:26 CST 2019
     */
    private Integer modifyid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xinyi_modifyhistory.modifyName
     *
     * @mbg.generated Sat Jul 06 15:36:26 CST 2019
     */
    private String modifyname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xinyi_modifyhistory.modifyManager
     *
     * @mbg.generated Sat Jul 06 15:36:26 CST 2019
     */
    private String modifymanager;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xinyi_modifyhistory.modifyDate
     *
     * @mbg.generated Sat Jul 06 15:36:26 CST 2019
     */
    private Date modifydate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xinyi_modifyhistory.modifyId
     *
     * @return the value of xinyi_modifyhistory.modifyId
     *
     * @mbg.generated Sat Jul 06 15:36:26 CST 2019
     */
    public Integer getModifyid() {
        return modifyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xinyi_modifyhistory.modifyId
     *
     * @param modifyid the value for xinyi_modifyhistory.modifyId
     *
     * @mbg.generated Sat Jul 06 15:36:26 CST 2019
     */
    public void setModifyid(Integer modifyid) {
        this.modifyid = modifyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xinyi_modifyhistory.modifyName
     *
     * @return the value of xinyi_modifyhistory.modifyName
     *
     * @mbg.generated Sat Jul 06 15:36:26 CST 2019
     */
    public String getModifyname() {
        return modifyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xinyi_modifyhistory.modifyName
     *
     * @param modifyname the value for xinyi_modifyhistory.modifyName
     *
     * @mbg.generated Sat Jul 06 15:36:26 CST 2019
     */
    public void setModifyname(String modifyname) {
        this.modifyname = modifyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xinyi_modifyhistory.modifyManager
     *
     * @return the value of xinyi_modifyhistory.modifyManager
     *
     * @mbg.generated Sat Jul 06 15:36:26 CST 2019
     */
    public String getModifymanager() {
        return modifymanager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xinyi_modifyhistory.modifyManager
     *
     * @param modifymanager the value for xinyi_modifyhistory.modifyManager
     *
     * @mbg.generated Sat Jul 06 15:36:26 CST 2019
     */
    public void setModifymanager(String modifymanager) {
        this.modifymanager = modifymanager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xinyi_modifyhistory.modifyDate
     *
     * @return the value of xinyi_modifyhistory.modifyDate
     *
     * @mbg.generated Sat Jul 06 15:36:26 CST 2019
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xinyi_modifyhistory.modifyDate
     *
     * @param modifydate the value for xinyi_modifyhistory.modifyDate
     *
     * @mbg.generated Sat Jul 06 15:36:26 CST 2019
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }
}